# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "20d7fd02a2ee01f8f73bddf13b44a6d1"
application_url = "https://rebbi-shirt-order.vercel.app"
embedded = true
name = "Base44 Integrations-Rebbi IVR"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_customers,read_discounts,write_draft_orders,read_draft_orders,read_fulfillments,write_fulfillments,read_inventory,read_locations,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_orders,write_orders,read_products,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-01"
