api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "rb-refund-stripe"
type = "ui_extension"
uid = "feb60a10-ba9a-46b6-87eb-483e02247e84"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.order-details.action.render"
